### ISSUE TITLE
Content of symlink dirs is not watched for changes 

### ISSUE THREAD

**Issue by jankrcal** [faktaoklimatu/web-core#162] opened 2022-04-08 13:27 UTC
Reproes with local build on Mac (but I am quite sure also on linux; curious about container builds).

When running jekyll, it rebuilds upon file changes which is super useful for local testing. This however does _not_ work for files with symlink parent. Examples:
 - changing search.json -> **works** (no symlink)
 - changing _explainers/emise-dychani.md -> **does not work** (_explainers is a symlink)
 - changing _infographics/emise/emise-cr.md -> **works** (emise is not a symlink)

This is a known limitation of jekyll-watch (https://github.com/jekyll/jekyll-watch/issues/89), I have a hacky PR to avoid that (https://github.com/faktaoklimatu/web-core/pull/161/files).

However, maybe an easier and slightly more robust fix would be to restructure the files in web-core and web-* so that there's only one symlink that has no immediate files within, i.e.

```
 web-cz
   local
     _infographics
     _explainers
    ...

 web-core
   local  -> symlink to ../local
     _infographics
     _explainers
     ...
```

WDYT?

**Comment by mukrop** [comment] 2022-04-15 09:44
I can confirm the same behaviour on Linux. I've noticed problems with automatic watch for quite some time but never really found time to debug that (since, for example, it works for all infographics due to our folder setup).

Seeing your hack in #161 and realizing all would be fixed by itself by adding the one extra folder, I'm quite inclined to go with that solution. As you write, it's a more robust and easier fix. On the downside, we'd gain one more click for everybody working with those folders. Although I'm not delighted by that, I think the benefits are worth it.

Any opinion of @mgrabovsky?

**Comment by jankrcal** [comment] 2022-04-19 11:54
Thanks for the comment. Unless @mgrabovsky protests, I'll turn it into a set of PRs when I have free time in the next couple weeks.

**Comment by mgrabovsky** [comment] 2022-04-19 20:21
Indeed, I agree with Martin – the hack with the extra directory proposed above appeals to me a wee bit more as well.

**Closed** 2022-06-10 08:29 UTC
